version: "3"
services:
  python: &python
    container_name: to_do_backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/app/backend
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres

  postgres:
    container_name: to_do_db
    image: postgres:12.3-alpine
    ports:
      - 5433:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /var/lib/postgresql/data

  frontend:
    container_name: to_do_frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    command: npm start
    volumes:
      - ./frontend:/app/frontend
    ports:
      - 3000:3000
    depends_on:
      - python
      - postgres
